/**
 * Init Command - Initialize CogniDocs configuration
 * Phase 1: Foundation
 */

import { writeFile } from 'fs/promises';
import { join } from 'path';
import inquirer from 'inquirer';
import chalk from 'chalk';
import { fileExists } from '@cognidocs/utils';

export interface InitOptions {
  force?: boolean;
  yes?: boolean;
}

export async function initCommand(options: InitOptions = {}): Promise<void> {
  console.log(chalk.blue('🚀 Initializing CogniDocs...\n'));

  const configPath = join(process.cwd(), 'cognidocs.config.js');

  // Check if config already exists
  if (!options.force && (await fileExists(configPath))) {
    console.log(chalk.yellow('⚠️  Configuration file already exists!'));
    console.log(chalk.gray(`   ${configPath}\n`));

    if (!options.yes) {
      const { overwrite } = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'overwrite',
          message: 'Do you want to overwrite it?',
          default: false,
        },
      ]);

      if (!overwrite) {
        console.log(chalk.gray('   Initialization cancelled.'));
        return;
      }
    }
  }

  let config: any;

  if (options.yes) {
    // Use defaults without prompting
    config = {
      entry: './src',
      output: './docs',
      theme: 'gitbook',
      darkMode: true,
      frameworks: ['react'],
      exclude: ['**/*.test.ts', '**/*.test.tsx', '**/node_modules/**', '**/dist/**'],
    };
  } else {
    // Interactive prompts
    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'entry',
        message: 'Entry point (source directory):',
        default: './src',
      },
      {
        type: 'input',
        name: 'output',
        message: 'Output directory for documentation:',
        default: './docs',
      },
      {
        type: 'list',
        name: 'theme',
        message: 'Choose a theme:',
        choices: [
          { name: 'Gitbook (recommended)', value: 'gitbook' },
          { name: 'Material', value: 'material' },
          { name: 'Read the Docs', value: 'readthedocs' },
          { name: 'Stripe', value: 'stripe' },
        ],
        default: 'gitbook',
      },
      {
        type: 'confirm',
        name: 'darkMode',
        message: 'Enable dark mode?',
        default: true,
      },
      {
        type: 'checkbox',
        name: 'frameworks',
        message: 'Select frameworks to support:',
        choices: [
          { name: 'React', value: 'react', checked: true },
          { name: 'Next.js', value: 'nextjs' },
          { name: 'Vue', value: 'vue' },
          { name: 'Svelte', value: 'svelte' },
        ],
      },
      {
        type: 'confirm',
        name: 'coverage',
        message: 'Enable coverage tracking?',
        default: true,
      },
    ]);

    config = {
      entry: answers.entry,
      output: answers.output,
      theme: answers.theme,
      darkMode: answers.darkMode,
      frameworks: answers.frameworks,
      exclude: ['**/*.test.ts', '**/*.test.tsx', '**/node_modules/**', '**/dist/**'],
    };

    if (answers.coverage) {
      config.coverage = {
        enabled: true,
        thresholds: {
          docs: 80,
          types: 90,
        },
      };
    }
  }

  // Generate config file content
  const configContent = `/**
 * CogniDocs Configuration
 * Generated by: cognidocs init
 */

export default ${JSON.stringify(config, null, 2)};
`;

  // Write config file
  await writeFile(configPath, configContent, 'utf-8');

  console.log(chalk.green('\n✅ Configuration created successfully!'));
  console.log(chalk.gray(`   ${configPath}\n`));
  console.log(chalk.blue('Next steps:'));
  console.log(chalk.gray('   1. Review and customize cognidocs.config.js'));
  console.log(chalk.gray('   2. Run: cognidocs build'));
  console.log(chalk.gray('   3. Run: cognidocs serve\n'));
}
