/**
 * CogniDocs Configuration
 * Generated by: cognidocs init
 */

export default {
  entry: './packages/parser/src',
  output: './docs',
  theme: 'gitbook',
  darkMode: true,
  frameworks: ['react'],
  exclude: ['**/*.test.ts', '**/*.test.tsx', '**/node_modules/**', '**/dist/**'],
};
