/**
 * CogniDocs Configuration
 * Generated by: cognidocs init
 */

export default {
  entry: './',
  output: './docs',
  theme: 'dracula',
  darkMode: true,
  frameworks: ['nextjs'],
  exclude: [
    '**/*.test.ts',
    '**/*.test.tsx',
    '**/node_modules/**',
    '**/dist/**',
    '**/.next/**',
    '**/.cognidocs/**',
  ],

  coverage: {
    enabled: true,
    thresholds: {
      docs: 80,
      types: 90,
    },
  },
};
