/**
 * CogniDocs Configuration
 * Generated by: cognidocs init
 */

export default {
  entry: './',
  output: './docs',
  theme: 'gitbook',
  darkMode: true,
  frameworks: ['nextjs'],
  exclude: ['**/*.test.ts', '**/*.test.tsx', '**/node_modules/**', '**/dist/**'],
};
